package com.github.adizcode.heartily.ui.theme

import androidx.compose.ui.graphics.Color

val mdThemeLightPrimary = Color(0xFFBE0039)
val mdThemeLightOnPrimary = Color(0xFFFFFFFF)
val mdThemeLightPrimaryContainer = Color(0xFFFFDADB)
val mdThemeLightOnPrimaryContainer = Color(0xFF40000D)
val mdThemeLightSecondary = Color(0xFF765658)
val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
val mdThemeLightSecondaryContainer = Color(0xFFFFDADB)
val mdThemeLightOnSecondaryContainer = Color(0xFF2C1517)
val mdThemeLightTertiary = Color(0xFF76592F)
val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
val mdThemeLightTertiaryContainer = Color(0xFFFFDDB3)
val mdThemeLightOnTertiaryContainer = Color(0xFF291800)
val mdThemeLightError = Color(0xFFBA1A1A)
val mdThemeLightErrorContainer = Color(0xFFFFDAD6)
val mdThemeLightOnError = Color(0xFFFFFFFF)
val mdThemeLightOnErrorContainer = Color(0xFF410002)
val mdThemeLightBackground = Color(0xFFFFFBFF)
val mdThemeLightOnBackground = Color(0xFF201A1A)
val mdThemeLightSurface = Color(0xFFFFFBFF)
val mdThemeLightOnSurface = Color(0xFF201A1A)
val mdThemeLightSurfaceVariant = Color(0xFFF4DDDD)
val mdThemeLightOnSurfaceVariant = Color(0xFF524344)
val mdThemeLightOutline = Color(0xFF857373)
val mdThemeLightInverseOnSurface = Color(0xFFFBEEED)
val mdThemeLightInverseSurface = Color(0xFF362F2F)
val mdThemeLightInversePrimary = Color(0xFFFFB2B7)
val mdThemeLightShadow = Color(0xFF000000)
val mdThemeLightSurfaceTint = Color(0xFFBE0039)

val mdThemeDarkPrimary = Color(0xFFFFB2B7)
val mdThemeDarkOnPrimary = Color(0xFF67001B)
val mdThemeDarkPrimaryContainer = Color(0xFF92002A)
val mdThemeDarkOnPrimaryContainer = Color(0xFFFFDADB)
val mdThemeDarkSecondary = Color(0xFFE6BDBE)
val mdThemeDarkOnSecondary = Color(0xFF44292B)
val mdThemeDarkSecondaryContainer = Color(0xFF5C3F41)
val mdThemeDarkOnSecondaryContainer = Color(0xFFFFDADB)
val mdThemeDarkTertiary = Color(0xFFE7C08E)
val mdThemeDarkOnTertiary = Color(0xFF432C06)
val mdThemeDarkTertiaryContainer = Color(0xFF5C421A)
val mdThemeDarkOnTertiaryContainer = Color(0xFFFFDDB3)
val mdThemeDarkError = Color(0xFFFFB4AB)
val mdThemeDarkErrorContainer = Color(0xFF93000A)
val mdThemeDarkOnError = Color(0xFF690005)
val mdThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val mdThemeDarkBackground = Color(0xFF201A1A)
val mdThemeDarkOnBackground = Color(0xFFECE0DF)
val mdThemeDarkSurface = Color(0xFF201A1A)
val mdThemeDarkOnSurface = Color(0xFFECE0DF)
val mdThemeDarkSurfaceVariant = Color(0xFF524344)
val mdThemeDarkOnSurfaceVariant = Color(0xFFD7C1C2)
val mdThemeDarkOutline = Color(0xFF9F8C8D)
val mdThemeDarkInverseOnSurface = Color(0xFF201A1A)
val mdThemeDarkInverseSurface = Color(0xFFECE0DF)
val mdThemeDarkInversePrimary = Color(0xFFBE0039)
val mdThemeDarkShadow = Color(0xFF000000)
val mdThemeDarkSurfaceTint = Color(0xFFFFB2B7)


val seed = Color(0xFFF22452)